[phases.setup]
nixPkgs = ["mvn", "openjdk21"]

[phases.build]
cmds = ["rm -rf target backend/target", "mvn clean package -DskipTests"]

[start]
cmd = "java -jar backend/target/jewellery-backend-0.0.2-SNAPSHOT.jar"
